### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by baynezy** [johnwyles/node-nest-api#7]
There appears to be a fatal bug in this project (#5), and two people have independently provided PRs for this.

#4 and #6 

The project owner @johnwyles has not responded to either.

So is this project abandoned?

**Comment by johnwyles** [comment]
I have saw to your requests and believe I merged in the two PR's you referred to correctly - I have not maintained this API in more than a year but if you do see something please fork / send me a PR and I will see to it it gets added - I must have missed the two you referred to.  Apologies and hopefully we can get this all straightened away so there is something functional and working for others like yourself.  Thanks for the ping - hope things go smoothly!

**Comment by baynezy** [comment]
Thanks @johnwyles

**Comment by johnwyles** [comment]
I just pushed up to NPM the new version (0.0.8) and pushed to github - let
me know if you see anything amiss

**Comment by baynezy** [comment]
@johnwyles - that seems ot be working thank you.
